---
name: Check

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test (Python ${{ matrix.python }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - '3.10'
          - '3.11'
        include:
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-latest
            os_name: macOS
          - os: windows-latest
            os_name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python }}
      - name: Test
        run: make test
  lint:
    name: Lint (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python }}
      - name: Lint
        run: make lint
  build:
    name: Build (Python ${{ matrix.python }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - '3.10'
          - '3.11'
        include:
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-latest
            os_name: macOS
          - os: windows-latest
            os_name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python }}
      - name: Build
        run: make build
