---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: dist/*
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist/*
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          files: dist/*
  pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install_dependencies: 'false'
      - name: Publish
        run: poetry publish --skip-existing -u $USERNAME -p $PASSWORD
        env:
          USERNAME: __token__
          PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
